// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public class PanelNames {
    
    public static string Panel01 {
        get {
            return "Panel01";
        }
    }
    
    public static string Panel04 {
        get {
            return "Panel04";
        }
    }
    
    public static string Panel02 {
        get {
            return "Panel02";
        }
    }
    
    public static string Panel03 {
        get {
            return "Panel03";
        }
    }
    
    public static string MainPanel {
        get {
            return "MainPanel";
        }
    }
    
    public static string SubGroupPanel {
        get {
            return "SubGroupPanel";
        }
    }
    
    public static string SubGroupA {
        get {
            return "SubGroupA";
        }
    }
    
    public static string SubGroupB {
        get {
            return "SubGroupB";
        }
    }
    
    public static string PopUpPanel {
        get {
            return "PopUpPanel";
        }
    }
    
    public static string RadiaMenuPanel {
        get {
            return "RadiaMenuPanel";
        }
    }
    
    public static string LuaPanel {
        get {
            return "LuaPanel";
        }
    }
    
    public static string ButtonOpenPanel {
        get {
            return "ButtonOpenPanel";
        }
    }
    
    public static string ButtonsPanel {
        get {
            return "ButtonsPanel";
        }
    }
    
    public static string InputPanel {
        get {
            return "InputPanel";
        }
    }
    
    public static string SingleImagePanel {
        get {
            return "SingleImagePanel";
        }
    }
    
    public static string TextInfoPanel {
        get {
            return "TextInfoPanel";
        }
    }
    
    public static string TipInfomation {
        get {
            return "TipInfomation";
        }
    }
    
    public static string WaitPopPanel {
        get {
            return "WaitPopPanel";
        }
    }
    
    public static string TestPanel {
        get {
            return "TestPanel";
        }
    }
    
    public static string RuntimePanel {
        get {
            return "RuntimePanel";
        }
    }
    
    public static string AnimTestPanel {
        get {
            return "AnimTestPanel";
        }
    }
    
    public static string LuaPanel01 {
        get {
            return "LuaPanel01";
        }
    }
    
    public static string InnerGroupTestPanel {
        get {
            return "InnerGroupTestPanel";
        }
    }
    
    public static string GenericTypePanel {
        get {
            return "GenericTypePanel";
        }
    }
    
    public static string VMUsePanel {
        get {
            return "VMUsePanel";
        }
    }
    
    public static string ControlPanel {
        get {
            return "ControlPanel";
        }
    }
    
    public static string ControlPanel_B {
        get {
            return "ControlPanel_B";
        }
    }
    
    public static string WorldUI {
        get {
            return "WorldUI";
        }
    }
}
