using BridgeUI.Binding;
/// <summary>
/// AutoGenerated!
/// </summary>
public class VM_VMUsePanel : ViewModelBase
{
    public PanelAction<UnityEngine.UI.Button> onClick
    {
        get
        {
            return GetValue<PanelAction<UnityEngine.UI.Button>>("onClick");
        }
        set
        {
            SetValue<PanelAction<UnityEngine.UI.Button>>("onClick", value);
        }
    }
    public System.String title
    {
        get
        {
            return GetValue<System.String>("title");
        }
        set
        {
            SetValue<System.String>("title", value);
        }
    }
    public System.String info
    {
        get
        {
            return GetValue<System.String>("info");
        }
        set
        {
            SetValue<System.String>("info", value);
        }
    }
    public UnityEngine.Font font_size
    {
        get
        {
            return GetValue<UnityEngine.Font>("font_size");
        }
        set
        {
            SetValue<UnityEngine.Font>("font_size", value);
        }
    }
    
}
