//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UIFacade : IUIFacade
{
	public virtual void Open(string panelName)
	{
		throw new System.NotImplementedException();
	}

}

