// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class PanelNames {
    
    public static string MainPanel {
        get {
            return "MainPanel";
        }
    }
    
    public static string Panel01 {
        get {
            return "Panel01";
        }
    }
    
    public static string Panel02 {
        get {
            return "Panel02";
        }
    }
    
    public static string Panel03 {
        get {
            return "Panel03";
        }
    }
    
    public static string Panel04 {
        get {
            return "Panel04";
        }
    }
}
